<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */


/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */

$helper = $this->helper('Solwin\Cpanel\Helper\Data');
$showsocial = $helper->getShowsocialicons();

$baseUrl = $helper->getBaseUrl();
$mediaurl = $helper->getMediaUrl() . 'social/';
$f_logo = $helper->getFooterlogo();
$footer_logo = $mediaurl . $helper->getFooterlogo();
$helper = $this->helper('Solwin\Cpanel\Helper\Data');
$mediasocialurl = $helper->getMediaUrl() . 'social/';
$newsletter_title = $helper->getFooternewslettertitle();
$newsletter_text = $helper->getFooternewslettertext();
$newsletter_show = $helper->getShowfooternewsletter();
?>
<div class="page-footer">
   
    <div class="page-main">
        <div class="cp-footer-container">
            <div class="cp-footer-row clearfix">
                
            
                <div class="cp-footer-main">
                    <div class="cp-fblock">
                        <div class="cp-ftitle">
                            <h3>
                                Customer center
                            </h3>
                        </div>
                        <div class="cp-fcontent">
                            <ul class="footer links">
                                <li class="nav item"><a href="<?php echo $baseUrl; ?>customer/account/">My Account</a></li>
                                <li class="nav item"><a href="<?php echo $baseUrl; ?>sales/order/history/">Orders</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="cp-footer-main">
                    <div class="cp-fblock">
                        <div class="cp-ftitle">
                            <h3>
                                <?php echo __('Information') ?>
                            </h3>
                        </div>
                        <div class="cp-fcontent">
                            <?php ?>
                            <ul class="footer links">
                                <li class="nav item"><a href="<?php echo $baseUrl; ?>privacy-policy">Privacy Policy</a></li>
                                <li class="nav item"><a href="<?php echo $baseUrl; ?>returns-policy">Returns Policy</a></li>
                                <li class="nav item"><a href="<?php echo $baseUrl; ?>terms-and-conditions">Terms and Conditions</a></li>
                                <li class="nav item"><a href="<?php echo $baseUrl; ?>delivery-policy">Delivery Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                
                <?php if ($newsletter_show) { ?>
               
                <?php } ?>
                <div class="cp-footer-main foot-cycle-motion">
                    <div class="cp-fblock">
                        <div class="cp-ftitle">
                            <h3>Cycle Motion</h3>                        
                        </div> 
                        <div class="foot-cont-info">
                            <p><a href="https://www.google.com.au/maps/place/u2%2F37+Action+Rd,+Malaga+WA+6090/@-31.8466696,115.8778633,17z/data=!3m1!4b1!4m5!3m4!1s0x2a32b1be417b8039:0x589815cb6dd78e3f!8m2!3d-31.8466696!4d115.880052" target="_blank"><?php echo $helper->getContactstoreaddress(); ?></a></p>
                            <p><a href="mailto:<?php echo $helper->getStorecontactemail(); ?>"><?php echo $helper->getStorecontactemail(); ?></a></p>
                            <p class="blue-text">(+61) 0480 273 171</p>
                            <p class="blue-text">Secondary Phone: <br>(+61) 0480 344 366</p>
                            <p class="blue-text">ABN:  80162266604</p>
                        </div>
                    </div>                
                </div>
            </div>
        </div>
    </div>
</div>
<?php
$enable = $helper->getShowsharingaddon();
$pubid = $helper->getAddthispubid();

if ($enable) {
    ?>
    
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=<?php echo $pubid; ?>" async="async"></script>
<?php } ?>
