<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getFrontendLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>
<div class="product attribute name">
    <h1 style="color: #633a8e" class="value"><?php /* @escapeNotVerified */ echo $_product->getName() ?></h1>
</div>
<?php if ($_attributeValue): ?>
<div class="product attribute <?php /* @escapeNotVerified */ echo $_className?>">
    <?php if ($_attributeLabel != 'none'): ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel?></strong><?php endif; ?>
    <div class="value" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute;?>><?php /* @escapeNotVerified */ echo $_attributeValue; ?></div>
</div>
<?php if($_product->getModelNumber()): ?>
<div class="product attribute model-number">
    <strong class="type"><?php echo __("Model Number: "); ?></strong>
    <div class="value"><?php echo $_product->getModelNumber(); ?></div>
</div>
<?php endif; ?>
<?php endif; ?>

<?php $_getMyAttr = $_product->getResource()->getAttribute('country_of_manufacture');
	$attrTestValue = $_getMyAttr->getFrontend()->getValue($_product);
?>
<?php if(trim($attrTestValue)): ?>
	<strong class="type"><?php echo __("Manufacturer: "); ?></strong>
    <div class="value"><?php echo $attrTestValue ?></div>
<?php endif ?>